name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest 
